[2024-06-10T14:09:01.749+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T14:09:01.774+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.consolidate_data manual__2024-06-10T14:08:28.852914+00:00 [queued]>
[2024-06-10T14:09:01.784+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.consolidate_data manual__2024-06-10T14:08:28.852914+00:00 [queued]>
[2024-06-10T14:09:01.785+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-10T14:09:01.804+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): consolidate_data> on 2024-06-10 14:08:28.852914+00:00
[2024-06-10T14:09:01.814+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-10T14:09:01.816+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2024-06-10T14:09:01.816+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'consolidate_data', 'manual__2024-06-10T14:08:28.852914+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmp084e130d']
[2024-06-10T14:09:01.817+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask consolidate_data
[2024-06-10T14:09:01.866+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_toll_data.consolidate_data manual__2024-06-10T14:08:28.852914+00:00 [running]> on host 2c4b4cb333a5
[2024-06-10T14:09:01.946+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='21521333@gm.uit.edu.vn' AIRFLOW_CTX_DAG_OWNER='quan' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='consolidate_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T14:08:28.852914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T14:08:28.852914+00:00'
[2024-06-10T14:09:01.947+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T14:09:02.003+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-10T14:09:02.004+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T14:09:02.014+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data, task_id=consolidate_data, run_id=manual__2024-06-10T14:08:28.852914+00:00, execution_date=20240610T140828, start_date=20240610T140901, end_date=20240610T140902
[2024-06-10T14:09:02.031+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T14:09:02.048+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-10T14:09:02.051+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
